# Generated by Django 2.2.6 on 2020-06-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='achieved_date',
            field=models.DateTimeField(null=True, verbose_name='date achieved'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='achieved_date',
            field=models.DateTimeField(null=True, verbose_name='date achieved'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='rewarded_date',
            field=models.DateTimeField(null=True, verbose_name='date rewarded'),
        ),
    ]
