# Generated by Django 3.0.7 on 2020-06-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200610_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='description',
            field=models.TextField(null=True, verbose_name='description of goal'),
        ),
    ]
