# Generated by Django 3.0.7 on 2020-06-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_milestone_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='photo',
            field=models.ImageField(null=True, upload_to='uploaded/%Y/%m/%d', verbose_name='reward photo'),
        ),
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.TextField(null=True, verbose_name='description of session'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.TextField(null=True, verbose_name='description of milestone'),
        ),
    ]
