# Generated by Django 3.0.7 on 2020-08-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_goal_percent_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='percent_complete',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='percentage complete'),
        ),
    ]
